RSpec 4 finish
ryuki7/rspec_app_exam pull request #1
Opened 2021-03-23 09:42 UTC by ryuki7

* Listening on tcp://127.0.0.1:49841
      一覧ページにアクセスした場合、Taskが表示されること
      Project詳細からTask一覧ページにアクセスした場合、Taskが表示されること
  Task新規作成
    正常系
      Taskが新規作成されること
  Task詳細
    正常系
      Taskが表示されること
  Task編集
    正常系
      Taskを編集した場合、一覧画面で編集後の内容が表示されること
      ステータスを完了にした場合、Taskの完了日に今日の日付が登録されること
      既にステータスが完了のタスクのステータスを変更した場合、Taskの完了日が更新されないこと
  Task削除
    正常系
      Taskが削除されること

Finished in 3.59 seconds (files took 2.09 seconds to load)
8 examples, 0 failures

2021-03-23 10:20 UTC, yuji91 requested changes
修正の際はコミットの単位を分けるようにお願いします！

コミットメッセージにはPrefixをつけるように意識しましょう。
https://www.tam-tam.co.jp/tipsnote/program/post16686.html

2021-03-23 10:20 UTC, yuji91 commented on spec/system/task_spec.rb
> +  let(:task) { create(:task, project_id: project.id) }
`association`をFactoryに定義すると`project_id`の記載は不要になります。
```suggestion
  let(:task) { create(:task) }
```

2021-03-23 10:20 UTC, yuji91 commented on spec/system/task_spec.rb
> +        new_window = window_opened_by { click_link 'View Todos' }
`switch_to_window(windows.last)`の１行でも`page`オブジェクトの対象を切り替えられることは知っておいてください。

2021-03-23 10:20 UTC, yuji91 commented on spec/system/task_spec.rb
> +        update_task = Task.first
`let!`であらかじめテストデータを用意できるので、そこで定義した値を呼び出す形式の方がコード量が減りますね。

2021-03-23 10:20 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(page).not_to have_content short_time(destroy_task.deadline)
元々確認していた項目が変わっているので`expect`の内容は変えずに修正できないか試してみてください。
ヒントは他のテストコードにも記載があります。`page.body`の内容をデバッグで確認してみてください。

2021-03-23 10:20 UTC, yuji91 commented on spec/system/task_spec.rb
> +        destroy_task = task
ここも`let!`を使うとコードの見栄えがよくなりますね。

2021-03-23 10:50 UTC, ryuki7 commented on Gemfile.lock
> +   2.2.6
変えた記憶が無いのですが、何をしたらこのように変わってしまうものなんですかね、、、

2021-03-24 11:07 UTC, ryuki7 commented on spec/system/task_spec.rb
> +        expect(page).not_to have_content short_time(destroy_task.deadline)
`bafc330b44251dacb9ae9020c9ef7c0660783568`  で修正しました。

2021-03-24 11:09 UTC, ryuki7 commented on spec/support/strftime.rb
> +end
`ff31e3e3774e6ed958ee7cf5900157134e03a5a9` でstrfttime.rb ファイルの削除をしました。

2021-03-24 11:10 UTC, ryuki7 commented on spec/system/task_spec.rb
> +  let(:task) { create(:task, project_id: project.id) }
`ce23fb34df0bff4838dc6437ec19827086f2d615` でassociation を利用しました。

2021-03-24 11:11 UTC, ryuki7 commented on spec/system/task_spec.rb
> +        new_window = window_opened_by { click_link 'View Todos' }
`3cee7d6c012f52ec51f7e8505329479afbe2b8b1`でswitch_to_window(windows.last)の１行で実装しました。

2021-03-24 11:12 UTC, ryuki7 commented on spec/system/task_spec.rb
> +        update_task = Task.first
`9c1a063d1e9733410d587bc284db8fadf2eb98d7`でlet で定義しました。

2021-03-24 11:13 UTC, ryuki7 commented on spec/system/task_spec.rb
> +        destroy_task = task
`028f9060eead23888884c53c28b90510c860446d` でテストデータを作成しました。

2021-03-25 10:19 UTC, yuji91 commented on Gemfile.lock
> +   2.2.6
`bundle install`または`bundle update`実行時に何かあったのでは無いかと予想します！

2021-03-25 10:21 UTC, yuji91 commented on spec/system/task_spec.rb
> +        update_task = Task.first
letでは基本的にはFactoryを実行するので、ここはまた指摘しておきます！

2021-03-26 04:39 UTC, yuji91 requested changes
気になった点を指摘しました！

2021-03-26 04:39 UTC, yuji91 commented on spec/system/task_spec.rb
> +    let(:update_task) { Task.first }
`update_task`と記載した場合に`update`処理が行われずに`Task.first`の結果が返ってくることに違和感はありませんか？
`let`で定義する処理は基本的には`Factory`の実行で済まないかどうかを検討してください。

2021-03-26 10:16 UTC, ryuki7 commented on spec/system/task_spec.rb
> +    let(:update_task) { Task.first }
update後のtaskという意味合いで定義してました、、、、
346221f で修正しました。

2021-03-26 10:17 UTC, ryuki7 commented on spec/system/task_spec.rb
> +    let!(:destroy_task) { create(:task) }
da61fe2 で定義名の変更をしました。

2021-03-26 10:24 UTC, yuji91 requested changes
1点コメントしました！

2021-03-26 10:24 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(find('.task_list')).to have_content short_time(Task.first.deadline)
`Task.first`はテストケース実施に当たってテストデータが余計に作成されると破綻するので、なるべく避けた方が良いです！
今回は`task`に`reload`を使うと更新後の状態で内容が取得できるので利用できるかと思います。
```suggestion
        expect(find('.task_list')).to have_content short_time(task.reload.deadline)
```

2021-03-26 11:03 UTC, ryuki7 commented on spec/system/task_spec.rb
> +        expect(find('.task_list')).to have_content short_time(Task.first.deadline)
そんな機能あるんですね！！知りませんでした！！
a71020a で修正しました。

2021-03-26 11:27 UTC, yuji91 approved these changes
LGTMです！

`reload`や`let!`など見慣れないコードが出てきた場合は、どのようなコードなのか調べておくようにしておくと良いですね。

2021-03-26 11:30 UTC, merged